cyclomatic_complexity: 12
file_length: 550
function_body_length: 80
function_parameter_count: 8
line_length: 150
type_body_length: 300
variable_name:
  min_length:
    error: 1
    warning: 1
  excluded:
    - N

disabled_rules:
  - valid_docs
  - force_try
  - force_cast
  - nesting

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage